# Generated by Django 2.2 on 2020-11-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratelimit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exceededlimitrecord",
            name="last_blocked_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Blocked At"),
        ),
    ]
